### ISSUE TITLE
Add/Change Brokenithm iOS TestFlight Link

### ISSUE THREAD

**Issue by OWCramer** [two-torial/two-torial#64]
It looks like the Brokenithm-iOS TestFlight link has expired and new builds haven't been pushed in a while. 

I created a new version of the iOS client which can be found here: https://testflight.apple.com/join/U6kwvETm using newer frameworks and standards. 

It still uses the original windows client so no other changes needed. 

Could we get this version added to or changed in the Docs?

**Comment by Aeph1edur** [comment]
Your minimum iOS requirement is a bit too high and will not work for most older devices or some people don’t want to update their iOS

I recommend to set iOS 15 as minimum or iOS 12 would be better cause that will supported most devices

**Comment by OWCramer** [comment]
I wish I could, but I'm currently using the "SpatialEventGesture" feature which was only introduced in iOS 18. I can look into back porting, but minimum version would probably only be iOS 16 or 17, and would take quite a bit of time (Which I don't have much off :( ). The app is made with SwiftUI which was only introduced in iOS 14, so anything older than that is completely out of the question. My version of the app is made to co-exist along the older one, so if people are on less than iOS 18, they can always side load the older one with the ipa. But I feel like having the option to use this mine through TestFlight, since the older one is unavailable atm, and with the cost of a newer OS, is a valid option.

**Comment by yxrei** [comment]
I'd personally add it alongside of the current link, it may be "outdated"/not available right now but removing it completely would be a bit too confusing I'd say.

**Comment by OWCramer** [comment]
> I'd personally add it alongside of the current link, it may be "outdated"/not available right now but removing it completely would be a bit too confusing I'd say.

I agree that's the best option and what I was initially going for.

**Comment by akitakedits** [comment]
> I'd personally add it alongside of the current link, it may be "outdated"/not available right now but removing it completely would be a bit too confusing I'd say.

This sound like the best solution. Linking to both, letting the readers pick their poison.
