### ISSUE TITLE
MDX-2024091000 Patches

### ISSUE THREAD

**Issue by TopherK** [two-torial/two-torial#65]
Ported using the port_sp2x_patches tool.
[MDX-66d95989_1bc399.json](https://github.com/user-attachments/files/17051487/MDX-66d95989_1bc399.json)

**Comment by yxrei** [comment]
Added. Would appreciate it if you could either PR or make an issue on [the sp2x patcher](https://github.com/two-torial/sp2xpatcher) but this worked now so no worries!

**Comment by akitakedits** [comment]
@TopherK Is this MDX 001 or 003?

**Comment by TopherK** [comment]
MDX-001
