### ISSUE TITLE
Any way to use Chuni hands on newer versions of chunithm

### ISSUE THREAD

**Issue by hedkne43rei0pow** [two-torial/two-torial#69]
Any way to use Chuni hands (or similar) on newer versions of chunithm such as luminous(plus) [https://github.com/logchan/chuni-hands](url)

**Comment by akitakedits** [comment]
GitHub issues aren't made to ask/answer questions about a game, please join our Discord for that.

**Comment by hedkne43rei0pow** [comment]
oh sorry I'll ask on the discord.
